language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.prod.dev -t sunil28/starbucks-backend .

script:
  - docker run -e CI=true sunil28/starbucks-backend mvn clean test