version: '3.0'

services:
  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    command: --lower_case_table_names=1
    volumes:
      - "./:/starbucks-backend:delegated"
    networks:
      - starbucks_network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  starbucks-backend:
    image: maven:3-jdk-8
    container_name: starbucks-backend
    volumes:
      - "./:/starbucks-backend:delegated"
      - "~/.m2:/root/.m2:delegated"
    working_dir: /starbucks-backend
    networks:
      - starbucks_network
    entrypoint: /bin/bash
    environment:
      - env=docker
      - MAVEN_OPTS=-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n
    ports:
      - "8080:8080"
      - "8000:8000"
    stdin_open: true
    tty: true
networks:
  starbucks_network: {}

